type: custom:power-flow-card-plus
entities:
  home:
    entity: sensor.home_power
    color_icon: solar
  fossil_fuel_percentage:
    entity: sensor.battery_soc
    icon: mdi:pine-tree
    color_icon: true
  solar:
    icon: mdi:solar-panel-large
    entity: sensor.solar_power
  battery:
    name: Bateria
    icon: mdi:bat
    entity:
      consumption: sensor.battery_charge_power
      production: sensor.battery_discharge_power
  individual:
    - entity: sensor.grid_import_power
      icon: mdi:transmission-tower-import
      color: "#80b8ff"
      name: Grid Import
      color_icon: false
    - entity: sensor.grid_export_power
      icon: mdi:transmission-tower-export
      color: "#ff8080"
      name: Grid Export
      color_icon: true
w_decimals: 0
kw_decimals: 2
min_flow_rate: 0.9
max_flow_rate: 6
watt_threshold: 10000
clickable_entities: true
title: Power Flow Card Plus