type: custom:power-flow-card-plus
entities:
  grid:
    entity: sensor.jackery_grid_net_power
    display_state: two_way
    color_circle: true
  solar:
    entity: sensor.jackery_solar_power
  battery:
    entity:
      consumption: sensor.jackery_calc_battery_charge_power
      production: sensor.jackery_calc_battery_discharge_power
    state_of_charge: sensor.jackery_battery_soc
    display_state: two_way
    color_circle: true
  home:
    entity: sensor.jackery_home_power
    color_icon: true
  individual:
    - entity: sensor.jackery_eps_output_power
      secondary_info: {}
      icon: mdi:power-plug
      name: EPS
      color_value: true
      display_zero: true
      color_icon: true
watt_threshold: 10000
display_zero_lines:
  mode: show
  transparency: 50
  grey_color:
    - 189
    - 189
    - 189
clickable_entities: true